version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      cargo-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 3
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
